
services:
  xload-dev-mysql:
    image: mysql:8.0.33
    container_name: xload-dev-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: backend
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ./data/:/tmp/data/
      - xload-dev-mysql-data:/var/lib/mysql

    command: --default-authentication-plugin=mysql_native_password
    networks:
      - xload-network

  xload-dev-postgres:
    image: postgis/postgis:17-3.5
    container_name: xload-dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sparx
    ports:
      - "5436:5432"
    volumes:
      - ./pg.sql:/docker-entrypoint-initdb.d/init.sql
      - xload-dev-postgres-data:/var/lib/postgresql/data
    networks:
      - xload-network

volumes:
  xload-dev-mysql-data:
    name: xload-dev-mysql-data
  xload-dev-postgres-data:
    name: xload-dev-postgres-data

networks:
  xload-network:
    external: true



https://www.patreon.com/posts/early-sccess-how-105189769?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_fan&utm_content=web_share
https://www.patreon.com/posts/early-access-oil-90066204?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_fan&utm_content=web_share
https://www.patreon.com/posts/early-access-how-87922349?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_fan&utm_content=web_share
https://www.patreon.com/posts/early-access-how-87922349?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_fan&utm_content=web_share
https://www.patreon.com/posts/early-access-85397233?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_fan&utm_content=web_share
https://www.patreon.com/posts/early-access-82214418?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_fan&utm_content=web_share
https://www.patreon.com/posts/early-access-79343989?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_fan&utm_content=web_share
https://www.patreon.com/posts/early-access-to-76889730?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_fan&utm_content=web_share
https://www.patreon.com/posts/exclusive-video-75610216?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_fan&utm_content=web_share
https://www.patreon.com/posts/studio-cam-1-73647015?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_fan&utm_content=web_share
